/**
 * This class is generated by jOOQ
 */
package com.github.treetips.domain.model;


import com.github.treetips.domain.model.tables.Area;
import com.github.treetips.domain.model.tables.JavaType;
import com.github.treetips.domain.model.tables.Prefecture;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * エリアマスタ
	 */
	public static final Area AREA = com.github.treetips.domain.model.tables.Area.AREA;

	/**
	 * java型確認マスタ
	 */
	public static final JavaType JAVA_TYPE = com.github.treetips.domain.model.tables.JavaType.JAVA_TYPE;

	/**
	 * 都道府県マスタ
	 */
	public static final Prefecture PREFECTURE = com.github.treetips.domain.model.tables.Prefecture.PREFECTURE;
}
