/**
 * This class is generated by jOOQ
 */
package com.github.treetips.domain.model;


import com.github.treetips.domain.model.tables.Area;
import com.github.treetips.domain.model.tables.JavaType;
import com.github.treetips.domain.model.tables.Prefecture;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

	private static final long serialVersionUID = -1325933963;

	/**
	 * The reference instance of <code>test</code>
	 */
	public static final Test TEST = new Test();

	/**
	 * No further instances allowed
	 */
	private Test() {
		super("test");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Area.AREA,
			JavaType.JAVA_TYPE,
			Prefecture.PREFECTURE);
	}
}
