/**
 * This class is generated by jOOQ
 */
package com.github.treetips.domain.model.tables.records;


import com.github.treetips.domain.model.tables.Area;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * エリアマスタ
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AreaRecord extends UpdatableRecordImpl<AreaRecord> implements Record2<Byte, String> {

	private static final long serialVersionUID = 1844285508;

	/**
	 * Setter for <code>test.area.area_cd</code>. エリアコード
	 */
	public void setAreaCd(Byte value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>test.area.area_cd</code>. エリアコード
	 */
	public Byte getAreaCd() {
		return (Byte) getValue(0);
	}

	/**
	 * Setter for <code>test.area.area_name</code>. エリア名
	 */
	public void setAreaName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>test.area.area_name</code>. エリア名
	 */
	public String getAreaName() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Byte> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Byte, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Byte, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field1() {
		return Area.AREA.AREA_CD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Area.AREA.AREA_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value1() {
		return getAreaCd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getAreaName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AreaRecord value1(Byte value) {
		setAreaCd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AreaRecord value2(String value) {
		setAreaName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AreaRecord values(Byte value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AreaRecord
	 */
	public AreaRecord() {
		super(Area.AREA);
	}

	/**
	 * Create a detached, initialised AreaRecord
	 */
	public AreaRecord(Byte areaCd, String areaName) {
		super(Area.AREA);

		setValue(0, areaCd);
		setValue(1, areaName);
	}
}
