/**
 * This class is generated by jOOQ
 */
package com.github.treetips.domain.model.tables;


import com.github.treetips.domain.model.Keys;
import com.github.treetips.domain.model.Test;
import com.github.treetips.domain.model.tables.records.AreaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * エリアマスタ
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Area extends TableImpl<AreaRecord> {

	private static final long serialVersionUID = -1102509954;

	/**
	 * The reference instance of <code>test.area</code>
	 */
	public static final Area AREA = new Area();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AreaRecord> getRecordType() {
		return AreaRecord.class;
	}

	/**
	 * The column <code>test.area.area_cd</code>. エリアコード
	 */
	public final TableField<AreaRecord, Byte> AREA_CD = createField("area_cd", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "エリアコード");

	/**
	 * The column <code>test.area.area_name</code>. エリア名
	 */
	public final TableField<AreaRecord, String> AREA_NAME = createField("area_name", org.jooq.impl.SQLDataType.VARCHAR.length(191).nullable(false), this, "エリア名");

	/**
	 * Create a <code>test.area</code> table reference
	 */
	public Area() {
		this("area", null);
	}

	/**
	 * Create an aliased <code>test.area</code> table reference
	 */
	public Area(String alias) {
		this(alias, AREA);
	}

	private Area(String alias, Table<AreaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Area(String alias, Table<AreaRecord> aliased, Field<?>[] parameters) {
		super(alias, Test.TEST, aliased, parameters, "エリアマスタ");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AreaRecord> getPrimaryKey() {
		return Keys.KEY_AREA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AreaRecord>> getKeys() {
		return Arrays.<UniqueKey<AreaRecord>>asList(Keys.KEY_AREA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Area as(String alias) {
		return new Area(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Area rename(String name) {
		return new Area(name, null);
	}
}
