/**
 * This class is generated by jOOQ
 */
package com.github.treetips.domain.model.tables;


import com.github.treetips.domain.model.Keys;
import com.github.treetips.domain.model.Test;
import com.github.treetips.domain.model.tables.records.PrefectureRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 都道府県マスタ
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Prefecture extends TableImpl<PrefectureRecord> {

	private static final long serialVersionUID = -695484823;

	/**
	 * The reference instance of <code>test.prefecture</code>
	 */
	public static final Prefecture PREFECTURE = new Prefecture();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PrefectureRecord> getRecordType() {
		return PrefectureRecord.class;
	}

	/**
	 * The column <code>test.prefecture.area_cd</code>. エリアコード
	 */
	public final TableField<PrefectureRecord, Byte> AREA_CD = createField("area_cd", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "エリアコード");

	/**
	 * The column <code>test.prefecture.prefecture_cd</code>. 都道府県コード
	 */
	public final TableField<PrefectureRecord, Byte> PREFECTURE_CD = createField("prefecture_cd", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "都道府県コード");

	/**
	 * The column <code>test.prefecture.prefecture_name</code>. 都道府県名
	 */
	public final TableField<PrefectureRecord, String> PREFECTURE_NAME = createField("prefecture_name", org.jooq.impl.SQLDataType.VARCHAR.length(191).nullable(false), this, "都道府県名");

	/**
	 * Create a <code>test.prefecture</code> table reference
	 */
	public Prefecture() {
		this("prefecture", null);
	}

	/**
	 * Create an aliased <code>test.prefecture</code> table reference
	 */
	public Prefecture(String alias) {
		this(alias, PREFECTURE);
	}

	private Prefecture(String alias, Table<PrefectureRecord> aliased) {
		this(alias, aliased, null);
	}

	private Prefecture(String alias, Table<PrefectureRecord> aliased, Field<?>[] parameters) {
		super(alias, Test.TEST, aliased, parameters, "都道府県マスタ");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PrefectureRecord> getPrimaryKey() {
		return Keys.KEY_PREFECTURE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PrefectureRecord>> getKeys() {
		return Arrays.<UniqueKey<PrefectureRecord>>asList(Keys.KEY_PREFECTURE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Prefecture as(String alias) {
		return new Prefecture(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Prefecture rename(String name) {
		return new Prefecture(name, null);
	}
}
